#! /usr/bin/env python

import argparse

import matplotlib.pyplot as plt
import pandas as pd


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("fin", type=str)
    parser.add_argument("fout", type=str)
    return parser.parse_args()

def plot(args):
    with open(args.fin) as f:
        fnames = [line.strip() for line in f.readlines()]

    n_coress = []
    times = []
    for fname in fnames:
        df = pd.read_csv(fname)
        n_coress.append(df.n_cores)
        times.append(df.tottime / df.repeats)

    plt.plot(n_coress, times)
    plt.scatter(n_coress, times, color="k", marker="x")

    plt.xlabel("# cores")
    plt.ylabel("Time (s)")

    plt.yscale("log")

    plt.tight_layout()
    plt.savefig(args.fout)


if __name__ == "__main__":
    args = parse_args()
    plot(args)